//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <AppKit/NSCGSWindow.h>

@class NSCGSWindowCornerMask, NSDictionary;

__attribute__((visibility("hidden")))
@interface _NSCGSWindow : NSCGSWindow
{
    unsigned int _windowID;
    void *_deviceID;
    unsigned short _flags;
    struct CGSRegionObject *_shape;
    struct CGSRegionObject *_opaqueShape;
    struct CGSRegionObject *_eventShape;
    NSCGSWindowCornerMask *_cornerMask;
    NSDictionary *_shadowProperties;
    double _opacity;
    double _backdropBleedFraction;
    int _level;
    unsigned int _backdropsAreFrozen:1;
    NSDictionary *_freezeOptions;
}

- (void)thaw;
- (void)freezeWithOptions:(id)arg1;
- (void)reassociateWithSpacesByGeometry;
- (void)_setBackdropBleedFraction:(double)arg1;
- (double)_backdropBleedFraction;
- (void)_setBackdropsAreFrozen:(BOOL)arg1;
- (BOOL)_backdropsAreFrozen;
- (void)setShadowProperties:(id)arg1;
- (id)shadowProperties;
- (void)setCornerMask:(id)arg1;
- (id)cornerMask;
- (void)setEventShape:(struct CGSRegionObject *)arg1;
- (struct CGSRegionObject *)eventShape;
- (void)setOpaqueShape:(struct CGSRegionObject *)arg1;
- (struct CGSRegionObject *)opaqueShape;
- (void)setOpacity:(double)arg1;
- (double)opacity;
- (void)setLevel:(int)arg1;
- (int)level;
- (struct CGSize)size;
- (void)setFrame:(struct CGRect)arg1;
- (struct CGRect)frame;
- (void)setShape:(struct CGSRegionObject *)arg1;
- (struct CGSRegionObject *)shape;
- (struct CGImage *)imageInRect:(struct CGRect)arg1;
- (unsigned int)windowID;
- (id)description;
- (void)finalize;
- (void)dealloc;
- (id)initWithWindowID:(unsigned int)arg1;
- (id)init;
- (id)initWithConnectionID:(unsigned int)arg1;

@end

