//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableDictionary, NSPointerArray;

__attribute__((visibility("hidden")))
@interface _NSCGSTransaction : NSObject
{
    NSPointerArray *_preCommitActions;
    NSPointerArray *_postCommitActions;
    NSMutableDictionary *_objects;
    const void *_disableUpdatesToken;
    unsigned int _synchronous:1;
}

+ (id)currentTransaction;
- (void)disableUpdates;
@property(getter=isSynchronous) BOOL synchronous;
- (void)synchronize;
- (void)setObject:(id)arg1 forKey:(id)arg2;
- (id)objectForKey:(id)arg1;
- (void)addPostCommitAction:(CDUnknownBlockType)arg1;
- (void)appendAction:(CDUnknownBlockType)arg1;
- (void)prependAction:(CDUnknownBlockType)arg1;
- (void)finalize;
- (void)dealloc;
- (id)init;

@end

