//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <AppKit/NSCGSWindowBackingStore.h>

__attribute__((visibility("hidden")))
@interface _NSCGSWindowBackingStore : NSCGSWindowBackingStore
{
    unsigned int _windowID;
    void *_deviceID;
    unsigned char _flags;
    double _scale;
    unsigned int _depth;
    unsigned int _workingDepth;
    struct CGColorSpace *_colorSpace;
    struct CGColorSpace *_workingColorSpace;
    unsigned int _opaque:1;
    unsigned int _keepsExcessAllocation;
    unsigned int _attached:1;
    struct _opaque_pthread_mutex_t _bufferMutex;
    struct CGSize _backBufferSize;
    unsigned int _backBufferDepth;
    double _backBufferScale;
    struct CGColorSpace *_backBufferColorSpace;
    struct CGContextDelegate *_backBuffer;
    struct CGSRegionObject *_backBufferDefinedShape;
    struct CGSRegionObject *_flushShape;
    unsigned int _backBufferSeed;
}

- (struct CGContext *)drawingContext;
- (struct CGImage *)imageInRect:(struct CGRect)arg1;
- (void)setKeepsExcessAllocation:(BOOL)arg1;
- (BOOL)keepsExcessAllocation;
- (void)setDepth:(unsigned int)arg1;
- (unsigned int)depth;
- (void)setColorSpace:(struct CGColorSpace *)arg1;
- (struct CGColorSpace *)colorSpace;
- (void)setOpaque:(BOOL)arg1;
- (BOOL)isOpaque;
- (void)setScale:(double)arg1;
- (double)scale;
- (void)setAttached:(BOOL)arg1;
- (BOOL)isAttached;
- (void)setWorkingDepth:(unsigned int)arg1;
- (unsigned int)workingDepth;
- (void)setWorkingColorSpace:(struct CGColorSpace *)arg1;
- (struct CGColorSpace *)workingColorSpace;
- (struct CGSize)size;
- (void)finalize;
- (void)dealloc;
- (id)initWithWindowID:(unsigned int)arg1;

@end

