//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <AppKit/NSPanel.h>

@class NSToolbarFullScreenWindowManager;

__attribute__((visibility("hidden")))
@interface _NSFullScreenTileDividerWindow : NSPanel
{
    NSToolbarFullScreenWindowManager *_manager;
    struct CGRect _dividerRect;
    unsigned long long _edge;
    unsigned long long _parentSpace;
    unsigned long long _tileSpace;
    unsigned long long _verticalIndex;
    unsigned long long _horizontalIndex;
}

- (id)_hitTestWithHysteresisCheck:(struct CGPoint)arg1 forEvent:(id)arg2 allowWindowDragging:(char *)arg3;
- (struct CGRect)_windowResizeEventHandlingRectForRect:(struct CGRect)arg1;
- (BOOL)performDividerDragWithEvent:(id)arg1;
- (BOOL)drivingLiveResize;
- (void)dealloc;
- (void)disableAutomaticTermination;
- (void)enableAutomaticTermination;
- (struct CGRect)constrainFrameRect:(struct CGRect)arg1 toScreen:(id)arg2;
- (unsigned long long)horizontalIndex;
- (unsigned long long)verticalIndex;
- (unsigned long long)edge;
- (id)manager;
- (unsigned long long)tileSpaceID;
- (unsigned long long)parentSpaceID;
- (void)_setWindowTag;
- (id)initWithDividerRect:(struct CGRect)arg1 edge:(unsigned long long)arg2 parentSpace:(unsigned long long)arg3 tileSpace:(unsigned long long)arg4 manager:(id)arg5;

@end

