//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <AppKit/NSView.h>

@class NSTrackingArea, _NSFullScreenTileOverlayWindow;

__attribute__((visibility("hidden")))
@interface _NSFullScreenTileDividerWindowContentView : NSView
{
    NSTrackingArea *_cursorArea;
    BOOL _drivingLiveResize;
    BOOL _trackedInArea;
    _NSFullScreenTileOverlayWindow *_overlayWindow;
}

- (void)mouseExited:(id)arg1;
- (void)mouseEntered:(id)arg1;
- (void)updateTrackingAreas;
- (void)mouseDown:(id)arg1;
- (id)resizeCursor;
- (BOOL)drivingLiveResize;
- (BOOL)shouldDelayWindowOrderingForEvent:(id)arg1;
- (void)dealloc;
- (void)_removeOverlayWindow;
- (void)_updateOverlayWindow;
- (void)_setupOverlayWindow;

@end

