//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <AppKit/NSPanel.h>

@class CALayer, NSArray;

__attribute__((visibility("hidden")))
@interface _NSFullScreenTileOverlayWindow : NSPanel
{
    unsigned long long _activeTileID;
    unsigned long long _parentSpaceID;
    CALayer *_rootLayer;
    NSArray *_tileLayers;
    BOOL _beginningPresentation;
    BOOL _endingPresentation;
}

- (void)dealloc;
- (void)disableAutomaticTermination;
- (void)enableAutomaticTermination;
- (struct CGRect)constrainFrameRect:(struct CGRect)arg1 toScreen:(id)arg2;
- (void)updateOverlay;
- (void)endPresentationWithCompletionHandler:(CDUnknownBlockType)arg1;
- (void)beginPresentationWithCompletionHandler:(CDUnknownBlockType)arg1;
- (void)_setWindowTag;
- (BOOL)_shouldAutoFlattenLayerTree;
- (id)initWithActiveTileID:(unsigned long long)arg1 parentSpaceID:(unsigned long long)arg2 screen:(id)arg3;

@end

