//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSPressureConfiguration;

__attribute__((visibility("hidden")))
@interface _NSGestureRecognizerAuxiliary : NSObject
{
    NSPressureConfiguration *_activePressureConfiguration;
    struct {
        unsigned int sendsActionWhenPossible:1;
        unsigned int privateDelegateShouldSendActionWhenPossibleConcurrentlyWithRecognizer:1;
        unsigned int delegateShouldSendActionWhenPossibleConcurrentlyWithRecognizer:1;
        unsigned int viewIsUnsafeUnretained:1;
        unsigned int delegateIsUnsafeUnretained:1;
        unsigned int reserved:27;
    } _additionalFlags;
}

@end

