//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <AppKit/_NSScrollingMomentumCalculator.h>

__attribute__((visibility("hidden")))
@interface _NSScrollingMomentumCalculatorBase : _NSScrollingMomentumCalculator
{
    double _maxAllowedDuration;
    struct CGPoint _initialOrigin;
    struct CGPoint _initialVelocity;
    struct CGPoint _destinationOrigin;
    struct CGRect _docFrame;
    struct CGPoint _constrainedClippingOrigin;
    struct CGSize _clippingSize;
    struct CGSize _tolerance;
}

- (void)_calculateInitialVelocity;
- (void)_calculateDestination;
- (void)setTolerance:(struct CGSize)arg1;
- (struct CGSize)tolerance;
- (void)setDocumentFrame:(struct CGRect)arg1;
- (struct CGRect)documentFrame;
- (void)setDestinationOrigin:(struct CGPoint)arg1;
- (struct CGPoint)destinationOrigin;
- (void)setInitialOrigin:(struct CGPoint)arg1;
- (struct CGPoint)initialOrigin;
- (void)dealloc;
- (id)initWithInitialOrigin:(struct CGPoint)arg1 velocity:(struct CGPoint)arg2 documentFrame:(struct CGRect)arg3 constrainedClippingOrigin:(struct CGPoint)arg4 clippingSize:(struct CGSize)arg5 tolerance:(struct CGSize)arg6 maxDuration:(double)arg7;

@end

