//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface _NSScrollingMomentumCalculator : NSObject
{
}

- (struct CGPoint)positionAfterDuration:(double)arg1;
- (double)velocityAfterDuration:(double)arg1;
@property(readonly) double durationUntilStop;
@property struct CGRect documentFrame;
@property struct CGPoint destinationOrigin;
@property struct CGPoint initialOrigin;
@property struct CGSize tolerance;
- (id)initWithInitialOrigin:(struct CGPoint)arg1 velocity:(struct CGPoint)arg2 documentFrame:(struct CGRect)arg3 constrainedClippingOrigin:(struct CGPoint)arg4 clippingSize:(struct CGSize)arg5;
- (id)initWithInitialOrigin:(struct CGPoint)arg1 velocity:(struct CGPoint)arg2 documentFrame:(struct CGRect)arg3 constrainedClippingOrigin:(struct CGPoint)arg4 clippingSize:(struct CGSize)arg5 tolerance:(struct CGSize)arg6;
- (id)initWithInitialOrigin:(struct CGPoint)arg1 velocity:(struct CGPoint)arg2 documentFrame:(struct CGRect)arg3 constrainedClippingOrigin:(struct CGPoint)arg4 clippingSize:(struct CGSize)arg5 tolerance:(struct CGSize)arg6 maxDuration:(double)arg7;

@end

