//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSColorSpace, NSString, _NSScreenSharedInfo;

__attribute__((visibility("hidden")))
@interface _NSScreenAux : NSObject
{
    _NSScreenSharedInfo *sharedScreenInfo;
    NSColorSpace *colorSpace;
    double backingScaleFactor;
    struct CGSize resolution;
    NSString *UUIDString;
    BOOL isZeroScreen;
}

@end

