//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSMapTable, NSMutableArray, NSMutableDictionary, NSStackViewContainer;

__attribute__((visibility("hidden")))
@interface _NSStackViewPrivateData : NSObject
{
    NSArray *views;
    NSArray *detachedViews;
    NSMutableArray *viewsDetachedWithDeferredNotifications;
    NSMutableArray *viewsReattachedWithDeferredNotifications;
    NSStackViewContainer *leadingOrTopViewsManager;
    NSStackViewContainer *centerViewsManager;
    NSStackViewContainer *trailingOrBottomViewsManager;
    long long distribution;
    NSMutableDictionary *stackConstraintsDictionary;
    id centerLayoutGuide;
    NSMapTable *distributionSpacingLayoutGuides;
    id idealSizeLayoutGuide;
    float alignmentPriority;
    struct {
        unsigned int stackViewShouldNotAddConstraints:1;
        unsigned int stackViewFinishedDecoding:1;
        unsigned int stackViewDecodedWantingFlatHierarchy:1;
        unsigned int reserved:29;
    } _svFlags;
}

- (void)dealloc;

@end

