//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSCGSWindowLayerSurface, NSView, NSWindow;

__attribute__((visibility("hidden")))
@interface _NSViewLayerSurface : NSObject
{
    NSView *_view;
    NSWindow *_danglingWindow;
    NSWindow *_weakWindow;
    NSCGSWindowLayerSurface *_surface;
}

- (void)dealloc;
- (void)invalidate;
- (void)update;
- (id)initWithView:(id)arg1;

@end

