//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSISEngine, NSISVariable, NSLayoutDimension, NSLayoutXAxisAnchor, NSLayoutYAxisAnchor, NSMutableArray;

__attribute__((visibility("hidden")))
@interface _NSViewLayoutAux : NSObject
{
    NSISEngine *_engine;
    NSISVariable *_minXVariable;
    NSISVariable *_minYVariable;
    NSISVariable *_widthVariable;
    NSISVariable *_heightVariable;
    NSArray *_internalConstraints;
    NSArray *_constraintsExceptingSubviewAutoresizingConstraints;
    NSMutableArray *_layoutGuides;
    struct CGSize _oldSizeDuringLayoutDescent;
    NSLayoutXAxisAnchor *_leadingAnchor;
    NSLayoutXAxisAnchor *_trailingAnchor;
    NSLayoutXAxisAnchor *_leftAnchor;
    NSLayoutXAxisAnchor *_rightAnchor;
    NSLayoutYAxisAnchor *_topAnchor;
    NSLayoutYAxisAnchor *_bottomAnchor;
    NSLayoutDimension *_widthAnchor;
    NSLayoutDimension *_heightAnchor;
    NSLayoutXAxisAnchor *_centerXAnchor;
    NSLayoutYAxisAnchor *_centerYAnchor;
    NSLayoutYAxisAnchor *_firstBaselineAnchor;
    NSLayoutYAxisAnchor *_lastBaselineAnchor;
    struct {
        unsigned int _potentiallyHasDanglyConstraints:1;
        unsigned int _mightBePiercedByConstraint:1;
        unsigned int _doesNotTranslateAutoresizingMaskIntoConstraints:1;
        unsigned int _wantsToHostAutolayoutEngine:1;
        unsigned int _hostsAutolayoutEngine:1;
        unsigned int _resizingFromLayout:1;
        unsigned int _recursionGuard:1;
        unsigned int _baselineOffsetMayBeReferenced:1;
        unsigned int _constraintsReferencingBaselineOffsetNeedUpdating:1;
    } _flags;
}

- (void)dealloc;
- (id)init;

@end

