//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

__attribute__((visibility("hidden")))
@interface NSAppearanceAuxiliary : NSObject
{
    BOOL _preventArchiving;
    BOOL _allowsVibrancy;
    int _defaultBlendMode;
}

@property int defaultBlendMode; // @synthesize defaultBlendMode=_defaultBlendMode;
@property BOOL allowsVibrancy; // @synthesize allowsVibrancy=_allowsVibrancy;
@property BOOL preventArchiving; // @synthesize preventArchiving=_preventArchiving;

@end

