//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSCGSWindowBackingStore, NSCGSWindowCornerMask, NSDictionary;

__attribute__((visibility("hidden")))
@interface NSCGSWindow : NSObject
{
}

+ (id)windowWithWindowID:(unsigned int)arg1;
+ (id)window;
+ (id)windowWithConnectionID:(unsigned int)arg1;
+ (void)orderApplicationWindowsFront;
+ (void)setDisplayFlipOffset:(double)arg1;
+ (double)displayFlipOffset;
+ (void)setSynchronous:(BOOL)arg1;
+ (BOOL)isSynchronous;
+ (void)synchronize;
- (void)reassociateWithSpacesByGeometry;
- (struct CGImage *)imageInRect:(struct CGRect)arg1;
@property double backdropBleedFraction;
@property BOOL backdropsAreFrozen;
- (id)makeBackdrop;
- (id)makeLayerSurface;
- (id)makeLocallyRenderedLayerSurface;
@property(readonly, retain) NSCGSWindowBackingStore *backingStore;
@property BOOL hasBackingStore;
@property(readonly) struct CGSize size;
@property struct CGRect frame;
- (void)orderOut;
- (void)orderBelowWindow:(id)arg1;
- (void)orderAboveWindow:(id)arg1;
- (void)orderFront;
- (void)orderGroupOut;
- (void)orderGroupBelowWindow:(id)arg1;
- (void)orderGroupAboveWindow:(id)arg1;
- (void)orderGroupFront;
- (void)_orderGroupWithOperation:(int)arg1 relativeToWindow:(id)arg2;
- (void)_orderWithOperation:(int)arg1 relativeToWindow:(id)arg2;
- (void)orderGroupFrontConditionally:(double)arg1;
- (id)orderingGroup;
- (void)moveGroupByX:(double)arg1 Y:(double)arg2;
- (void)moveByX:(double)arg1 Y:(double)arg2;
@property(readonly, copy) NSArray *movementGroup;
- (void)thaw;
- (void)freezeWithOptions:(id)arg1;

// Remaining properties
@property(copy) NSCGSWindowCornerMask *cornerMask; // @dynamic cornerMask;
@property(copy) struct CGSRegionObject *eventShape; // @dynamic eventShape;
@property int level; // @dynamic level;
@property double opacity; // @dynamic opacity;
@property(copy) struct CGSRegionObject *opaqueShape; // @dynamic opaqueShape;
@property(copy) NSDictionary *shadowProperties; // @dynamic shadowProperties;
@property(copy) struct CGSRegionObject *shape; // @dynamic shape;
@property(readonly) unsigned int windowID; // @dynamic windowID;

@end

