//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <AppKit/NSView.h>

@interface NSColorPanelResizeDimple : NSView
{
}

- (BOOL)acceptsFirstMouse:(id)arg1;
- (void)dealloc;
- (BOOL)acceptsFirstResponder;
- (BOOL)isOpaque;
- (void)drawRect:(struct CGRect)arg1;
- (void)resetCursorRects;
- (BOOL)mouseDownCanMoveWindow;
- (void)mouseDragged:(id)arg1;
- (void)mouseDown:(id)arg1;

@end

