//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

__attribute__((visibility("hidden")))
@interface NSDockConnection : NSObject
{
    struct _xpc_connection_s *_connection;
    struct dispatch_queue_s *_queue;
}

+ (id)sharedConnection;
- (void)sendMessage:(void *)arg1 synchronous:(BOOL)arg2 replyHandler:(CDUnknownBlockType)arg3;
- (void)sendMessage:(void *)arg1;
- (void)_makeConnectionIfNeeded;
- (void)_makeConnectionIfNeededWithRetryInterval:(double)arg1 onDemand:(BOOL)arg2;
- (void)reactToDockAlive;
- (void)reactToDockDied;
- (void)startConnection;
- (id)init;
- (void)dealloc;
- (void)_processEvent:(void *)arg1;
- (void)_processTileResizeMessage:(void *)arg1;
- (void)_processExitFullscreenMessage:(void *)arg1;
- (void)_processTileWindowMessage:(void *)arg1;
- (void)sendFullScreenAddTileForParentSpace:(unsigned long long)arg1 newWindow:(long long)arg2 left:(BOOL)arg3 completionHandler:(CDUnknownBlockType)arg4;
- (void)sendFullScreenCanAddTileForParentSpace:(unsigned long long)arg1 newWindow:(long long)arg2 completionHandler:(CDUnknownBlockType)arg3;
- (void)sendFullScreenWindowDidResize:(long long)arg1;
- (void)sendFullScreenTitleForTransition:(id)arg1 title:(id)arg2;
- (void)sendFullScreenUpdateSubspaceForTransition:(id)arg1 participatingWindows:(id)arg2;
- (void)sendFullScreenRemoveForTransition:(id)arg1;
- (void)sendFullScreenUpdateSpaceForTransition:(id)arg1 participatingWindows:(id)arg2;
- (void)sendFullScreenCreateForTransition:(id)arg1 window:(long long)arg2 spaceName:(id)arg3 completionHandler:(CDUnknownBlockType)arg4;
- (void)sendFullScreenEnterForTransition:(id)arg1 window:(long long)arg2 spaceName:(id)arg3 backgroundWindows:(id)arg4 participatingWindows:(id)arg5 customAnimation:(BOOL)arg6 completionHandler:(CDUnknownBlockType)arg7;
- (void)sendFullScreenExitForTransition:(id)arg1 synchronous:(BOOL)arg2 window:(long long)arg3 exitForClose:(BOOL)arg4 backgroundWindows:(id)arg5 participatingWindows:(id)arg6 customAnimation:(BOOL)arg7 completionHandler:(CDUnknownBlockType)arg8;

@end

