//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableArray;

__attribute__((visibility("hidden")))
@interface NSDocumentControllerMainThreadUnblockerEntry : NSObject
{
    CDUnknownBlockType unblocker;
    NSMutableArray *pendingInterrupters;
    NSMutableArray *pendingInterrupterCompletionBlocks;
    struct dispatch_queue_s *queue;
    BOOL waitingForInterrupterCompletion;
    BOOL suspended;
}

+ (id)entryWithUnblocker:(CDUnknownBlockType)arg1 queue:(struct dispatch_queue_s *)arg2;
@property BOOL suspended; // @synthesize suspended;
- (void)transferBlockingInterruptersToUnblocker:(id)arg1;
- (void)whenPendingInterruptersHaveCompletedInvokeBlock:(CDUnknownBlockType)arg1;
- (void)enqueueBlockingInterrupter:(CDUnknownBlockType)arg1;
- (void)_invokeInterrupter:(CDUnknownBlockType)arg1;
- (void)finalize;
- (void)dealloc;

@end

