//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSEvent, NSImage, NSMenu, NSMenuItem, NSPopover, NSString, NSView;

@protocol NSMenuImpl <NSObject>
- (struct OpaqueMenuRef *)_principalMenuRef;
- (void)_menuItem:(NSMenuItem *)arg1 atIndex:(unsigned long long)arg2 didChangeRadialMenuTitleFrom:(NSString *)arg3 to:(NSString *)arg4;
- (void)_menuItem:(NSMenuItem *)arg1 atIndex:(unsigned long long)arg2 didChangeRadialMenuImageFrom:(NSImage *)arg3 to:(NSImage *)arg4;
- (void)_menuItem:(NSMenuItem *)arg1 atIndex:(unsigned long long)arg2 didChangeDestructiveFrom:(BOOL)arg3 to:(BOOL)arg4;
- (void)_menuItem:(NSMenuItem *)arg1 atIndex:(unsigned long long)arg2 didChangeAlternateFrom:(BOOL)arg3 to:(BOOL)arg4;
- (void)_showPopover:(NSPopover *)arg1 forMenuItem:(NSMenuItem *)arg2;
- (void)_menuDidRemoveAllItems:(NSArray *)arg1;
- (void)_cancelTrackingWithAnimation:(BOOL)arg1;
- (NSMenuItem *)targetedItem;

@optional
- (NSView *)_presentingView;
- (void)_popUpRadialMenu:(NSMenu *)arg1 withEvent:(NSEvent *)arg2 forView:(NSView *)arg3;
@end

