//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSImage, NSString;

@protocol NSRadialMenuItem <NSObject>
@property(readonly) NSString *_titleForRadialMenu;
@property(readonly) NSImage *_alternateImageForRingStyleRadialMenu;
@property(readonly) NSImage *_imageForRadialMenu;
@property(readonly, getter=isDestructive) BOOL destructive;
@property(readonly, getter=isSeparatorItem) BOOL separatorItem;
@property(readonly, getter=isHidden) BOOL hidden;
@property(readonly, getter=isEnabled) BOOL enabled;
@property(readonly) BOOL looksEnabled;
@property(readonly) NSString *title;
@end

