//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <AppKit/NSView.h>

@class NSCell;

__attribute__((visibility("hidden")))
@interface NSSegmentItemLabelView : NSView
{
    NSCell *_cell;
}

+ (id)_getParentSegmentedControlViewFromView:(id)arg1;
- (void)drawRect:(struct CGRect)arg1;
@property(readonly) NSCell *cell;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

@end

