//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <AppKit/NSControl.h>

@interface NSSegmentedControl : NSControl
{
    long long _reserved1;
    long long _reserved2;
    long long _reserved3;
    long long _reserved4;
}

+ (void)initialize;
- (double)doubleValueForSelectedSegment;
@property unsigned long long trackingMode;
@property(getter=isSpringLoaded) BOOL springLoaded;
- (void)updateCell:(id)arg1;
- (long long)_badgeValueForSegment:(long long)arg1;
- (void)_setBadgeValue:(long long)arg1 forSegment:(long long)arg2;
- (BOOL)_showsBadgeForSegment:(long long)arg1;
- (void)_setShowsBadge:(BOOL)arg1 forSegment:(long long)arg2;
- (void)_updateLayerMasksToBoundsFromView;
- (id)_highlightColorForCell:(id)arg1;
- (double)baselineOffsetFromBottom;
- (BOOL)_hasExtra10_11BordersInToolbars;
- (struct NSEdgeInsets)alignmentRectInsets;
- (BOOL)_inToolbar;
- (void)moveDown:(id)arg1;
@property long long segmentStyle;
- (void)viewDidMoveToWindow;
- (void)_updateHeightToReflectNewWindowStyleIfNecessary;
- (BOOL)isEnabledForSegment:(long long)arg1;
- (void)setEnabled:(BOOL)arg1 forSegment:(long long)arg2;
- (BOOL)isSelectedForSegment:(long long)arg1;
- (void)setSelected:(BOOL)arg1 forSegment:(long long)arg2;
- (id)menuForSegment:(long long)arg1;
- (void)setMenu:(id)arg1 forSegment:(long long)arg2;
- (id)labelForSegment:(long long)arg1;
- (void)setLabel:(id)arg1 forSegment:(long long)arg2;
- (void)setImageScaling:(unsigned long long)arg1 forSegment:(long long)arg2;
- (unsigned long long)imageScalingForSegment:(long long)arg1;
- (id)alternateImageForSegment:(long long)arg1;
- (void)setAlternateImage:(id)arg1 forSegment:(long long)arg2;
- (id)imageForSegment:(long long)arg1;
- (void)setImage:(id)arg1 forSegment:(long long)arg2;
- (double)widthForSegment:(long long)arg1;
- (void)setWidth:(double)arg1 forSegment:(long long)arg2;
- (long long)indexOfSelectedItem;
- (BOOL)selectSegmentWithTag:(long long)arg1;
@property long long selectedSegment;
@property long long segmentCount;
- (void)springLoadingExited:(id)arg1;
- (void)springLoadingHighlightChanged:(id)arg1;
- (void)springLoadingActivated:(BOOL)arg1 draggingInfo:(id)arg2;
- (unsigned long long)springLoadingUpdated:(id)arg1;
- (unsigned long long)springLoadingEntered:(id)arg1;
- (void)viewDidEndLiveResize;
- (void)_windowChangedKeyState;
- (void)_setWindow:(id)arg1;
- (void)_updateMenuUniquing;
- (void)moveRight:(id)arg1;
- (void)moveLeft:(id)arg1;
- (BOOL)acceptsFirstMouse:(id)arg1;
- (struct CGRect)_opaqueRectForWindowMoveWhenInTitlebar;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (BOOL)isFlipped;
- (void)_setSpringLoadsOnDrag:(BOOL)arg1;
- (BOOL)_springLoadsOnDrag;
- (id)ns_widgetType;

@end

