//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSAnimatablePropertyContainer.h"
#import "NSCoding.h"

@class NSDictionary, NSViewController;

@interface NSSplitViewItem : NSObject <NSAnimatablePropertyContainer, NSCoding>
{
    id _splitViewItemPrivateData;
    struct {
        unsigned int _collapsed:1;
        unsigned int _canCollapse:1;
        unsigned int _isOverlaid:1;
        unsigned int _revealsOnEdgeHoverInFullscreen:1;
        unsigned int _springLoaded:1;
        unsigned int _prefersPreservingSiblingSizesOnCollapse:1;
        unsigned int _reserved:26;
    } _flags;
}

+ (id)defaultAnimationForKey:(id)arg1;
+ (BOOL)automaticallyNotifiesObserversOfCollapsed;
+ (id)keyPathsForValuesAffectingSidebar;
+ (id)contentListWithViewController:(id)arg1;
+ (id)sidebarWithViewController:(id)arg1;
+ (id)splitViewItemWithViewController:(id)arg1;
- (id)animationForKey:(id)arg1;
@property(copy) NSDictionary *animations;
- (id)animator;
- (Class)_animatorClass;
@property(getter=isSpringLoaded) BOOL springLoaded;
- (BOOL)hasUserSetSize;
- (void)setHasUserSetSize:(BOOL)arg1;
- (void)setRevealsOnEdgeHoverInFullscreen:(BOOL)arg1;
- (BOOL)revealsOnEdgeHoverInFullscreen;
- (void)setAutoHidesWhenFullscreen:(BOOL)arg1;
- (BOOL)autoHidesWhenFullscreen;
- (BOOL)isAnimating;
- (void)_markAnimationEnd;
- (void)_markAnimationStart;
- (void)setPrefersImplicitAnimations:(BOOL)arg1;
- (BOOL)prefersImplicitAnimations;
- (BOOL)isOverlaid;
- (void)setOverlaid:(BOOL)arg1;
- (BOOL)_canLiveCollapse;
@property double preferredThicknessFraction;
- (void)setPreferredSizeRatio:(double)arg1;
- (double)preferredSizeRatio;
@property double automaticMaximumThickness;
- (void)setAutomaticMaximumSize:(double)arg1;
- (double)automaticMaximumSize;
@property double maximumThickness;
- (void)setMaximumSize:(double)arg1;
- (double)maximumSize;
@property double minimumThickness;
- (void)setMinimumSize:(double)arg1;
- (double)minimumSize;
- (BOOL)canOverlay;
- (BOOL)_wantsMaterialBackground;
- (float)_effectiveHoldingPriority;
- (id)_overrideHoldingPriority;
- (void)_setOverrideHoldingPriority:(id)arg1;
@property float holdingPriority;
- (id)_splitViewController;
- (void)_didChangeCollapsed:(BOOL)arg1;
- (void)_willChangeCollapsed;
- (void)_uncollapsePreferringOverlay;
- (void)setPrefersPreservingSiblingSizesOnCollapse:(BOOL)arg1;
- (BOOL)prefersPreservingSiblingSizesOnCollapse;
@property(getter=isCollapsed) BOOL collapsed;
@property BOOL canCollapse;
@property(retain) NSViewController *viewController;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (void)dealloc;
- (id)init;
- (BOOL)isSidebar;
- (void)setSidebar:(BOOL)arg1;
@property(readonly) long long behavior;
- (void)setBehavior:(long long)arg1;

@end

