//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <AppKit/NSView.h>

@class NSArray, NSDictionary;

@interface NSStackView : NSView
{
    id <NSStackViewDelegate> _delegate;
    long long _orientation;
    long long _alignment;
    struct NSEdgeInsets _edgeInsets;
    double _spacing;
    float _verticalClippingResistancePriority;
    float _horizontalClippingResistancePriority;
    float _verticalHuggingPriority;
    float _horizontalHuggingPriority;
    BOOL _unused;
    id _animator;
    NSDictionary *_animationsDictionary;
    id _private;
    struct {
        unsigned int _inDealloc:1;
        unsigned int _detachesHiddenViews:1;
        unsigned int _baselineRelativeArrangement:1;
        unsigned int _reserved:29;
    } _flags;
}

+ (id)defaultAnimationForKey:(id)arg1;
+ (BOOL)requiresConstraintBasedLayout;
+ (id)keyPathsForValuesAffectingAlignment;
+ (id)stackViewWithViews:(id)arg1;
+ (id)keyPathsForValuesAffectingArrangedSubviews;
@property id <NSStackViewDelegate> delegate; // @synthesize delegate=_delegate;
- (id)rightSpacer;
- (id)leftSpacer;
- (id)bottomSpacer;
- (id)topSpacer;
- (BOOL)_ib_is19704021Fixed;
- (id)currentSpacers;
- (id)currentContainers;
- (id)endViewsContainer;
- (id)middleViewsContainer;
- (id)beginningViewsContainer;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)_stopObservingView:(id)arg1;
- (void)_startObservingView:(id)arg1;
- (BOOL)_removesDetachedViewsFromSubviews;
@property BOOL detachesHiddenViews;
- (id)animationForKey:(id)arg1;
- (void)setAnimations:(id)arg1;
- (id)animations;
- (id)animator;
- (Class)_animatorClass;
- (void)_checkForDroppedViews;
- (BOOL)_hasActiveClippingOfLastView;
- (void)_deferringDetachAndReattachNotifications:(CDUnknownBlockType)arg1;
- (void)_didReattachViews:(id)arg1;
- (void)_willReattachViews:(id)arg1;
- (void)_didDetachViews:(id)arg1;
- (void)_willDetachViews:(id)arg1;
- (void)_reattachViews:(id)arg1;
- (void)_detachViews:(id)arg1;
- (long long)_gravityForContainer:(id)arg1;
- (id)_detachedViewsSortedByPriorityWithoutUnaddableViews;
- (id)_detachedViewsSortedByPriority;
- (id)_attachedViewsSortedByPriority;
- (float)visibilityPriorityForView:(id)arg1;
- (void)setVisibilityPriority:(float)arg1 forView:(id)arg2;
- (double)lastBaselineOffsetFromBottom;
- (double)_lastBaselineOffsetFromStackViewBottomForView:(id)arg1;
- (double)firstBaselineOffsetFromTop;
- (double)_firstBaselineOffsetFromStackViewTopForView:(id)arg1;
- (void)_invalidateBaselines;
- (BOOL)_nsib_shouldAddConstraints;
- (void)_nsib_setShouldAddConstraints:(BOOL)arg1;
- (void)layout;
- (void)nsis_valueOfVariable:(id)arg1 didChangeInEngine:(id)arg2;
- (void)updateConstraints;
- (void)_updateStackConstraints;
- (BOOL)_firstAndLastViewsAreFlushToEdges;
- (float)_effectiveStackingAxisHuggingPriority;
- (void)enumerateViewsIncludingDetached:(BOOL)arg1 usingBlock:(CDUnknownBlockType)arg2;
- (id)_constraintsForConstraintType:(id)arg1;
- (void)_refreshConstraintsForConstraintType:(id)arg1;
- (void)setUserInterfaceLayoutDirection:(long long)arg1;
- (void)_createOrDestroyDistributionSpacingLayoutGuides;
- (BOOL)_requiresIdealSizingGuide;
- (long long)_numberOfDistributionGuidesRequired;
- (void)_createOrDestroyCenterLayoutGuideIfNeeded;
- (BOOL)_viewsAreCentered;
- (BOOL)_hasEffectiveGravityAreas;
- (void)_removeStackViewLayoutGuide:(id)arg1;
- (id)_createAndAddStackViewLayoutGuideWithIdentifier:(id)arg1;
- (void)setViews:(id)arg1 inGravity:(long long)arg2;
- (id)viewsInGravity:(long long)arg1;
@property(readonly, copy) NSArray *detachedViews;
- (id)attachedViews;
@property(readonly, copy) NSArray *views;
- (void)_removeView:(id)arg1 animated:(BOOL)arg2 removeFromViewHierarchy:(BOOL)arg3;
- (void)_removeView:(id)arg1 animated:(BOOL)arg2;
- (void)removeView:(id)arg1;
- (void)_insertView:(id)arg1 atIndex:(unsigned long long)arg2 inGravity:(long long)arg3 animated:(BOOL)arg4;
- (void)insertView:(id)arg1 atIndex:(unsigned long long)arg2 inGravity:(long long)arg3;
- (void)addView:(id)arg1 inGravity:(long long)arg2;
- (void)replaceSubview:(id)arg1 with:(id)arg2;
- (void)willRemoveSubview:(id)arg1;
- (id)trailingOrBottomViewsManager;
- (id)centerViewsManager;
- (id)leadingOrTopViewsManager;
- (id)_gravityContainerContainingView:(id)arg1;
- (double)effectiveSpacingAfterView:(id)arg1;
- (double)customSpacingAfterView:(id)arg1;
- (void)setCustomSpacing:(double)arg1 afterView:(id)arg2;
- (void)_setCustomSpacing:(double)arg1 afterView:(id)arg2 animated:(BOOL)arg3;
- (void)setHasEqualSpacing:(BOOL)arg1;
- (BOOL)hasEqualSpacing;
@property long long distribution;
- (void)_setEdgeInsets:(struct NSEdgeInsets)arg1 animated:(BOOL)arg2;
@property struct NSEdgeInsets edgeInsets;
@property double spacing;
- (void)_setSpacing:(double)arg1 animated:(BOOL)arg2;
- (void)setTransverseAlignmentPriority:(float)arg1;
- (float)transverseAlignmentPriority;
- (void)setSecondaryAlignmentPriority:(float)arg1;
- (float)secondaryAlignmentPriority;
- (void)setAlignmentPriority:(float)arg1;
- (float)alignmentPriority;
- (void)setTransverseAlignment:(long long)arg1;
- (long long)transverseAlignment;
- (void)setPerpendicularAlignment:(long long)arg1;
- (long long)perpendicularAlignment;
- (void)setSecondaryAlignment:(long long)arg1;
- (long long)secondaryAlignment;
@property long long alignment;
- (id)_explicitlySetUserInterfaceLayoutDirection;
- (void)setClippingResistancePriority:(float)arg1 forOrientation:(long long)arg2;
- (float)clippingResistancePriorityForOrientation:(long long)arg1;
- (void)setHuggingPriority:(float)arg1 forOrientation:(long long)arg2;
- (float)huggingPriorityForOrientation:(long long)arg1;
@property long long orientation;
- (BOOL)_isVertical;
- (void)dealloc;
- (void)encodeWithCoder:(id)arg1;
- (void)_finishedMakingConnections;
- (void)_addSubviewsAndPreserveAndPreserveAncestorConstraints:(id)arg1;
- (BOOL)_stackViewDecodedWantingFlatHierarchy;
- (BOOL)_stackViewFinishedDecoding;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
@property(readonly, copy) NSArray *arrangedSubviews;
- (void)insertArrangedSubview:(id)arg1 atIndex:(long long)arg2;
- (void)removeArrangedSubview:(id)arg1;
- (void)addArrangedSubview:(id)arg1;
@property(getter=isBaselineRelativeArrangement) BOOL baselineRelativeArrangement;
- (void)awakeFromNib;

@end

