//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSTextAttachment.h"

@interface NSTextAttachment (NSTextView_ForceEvents)
- (id)_immediateActionAnimationControllerForCharacterAtIndex:(unsigned long long)arg1 inTextView:(id)arg2;
- (BOOL)prepareActionMenu:(id)arg1 forTextView:(id)arg2 atCharacterIndex:(unsigned long long)arg3 withEvent:(id)arg4;
@end

