//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSStringDrawingContext.h"

@class NSTextFieldCell;

__attribute__((visibility("hidden")))
@interface NSTextFieldCellStringDrawingContext : NSStringDrawingContext
{
    NSTextFieldCell *_owner;
}

@property __weak NSTextFieldCell *owner; // @synthesize owner=_owner;
- (void)setFirstBaselineOffset:(double)arg1;

@end

