//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <AppKit/NSControl.h>

#import "NSAccessibilityNavigableStaticText.h"
#import "NSUserInterfaceValidations.h"

@class NSAttributedString, NSColor, NSNumber, NSString;

@interface NSTextField : NSControl <NSUserInterfaceValidations, NSAccessibilityNavigableStaticText>
{
    id _delegate;
    SEL _errorAction;
    double _maxLayoutWidth;
    long long _maximumNumberOfLines;
    BOOL _finishedFirstConstraintsPass;
    BOOL _baselineParametersDidChange;
    double _firstBaselineOffsetFromTop;
    NSNumber *_layoutEngineWidth;
    NSNumber *_cachedLayoutEngineWidth;
    struct CGSize _cachedIntrinsicContentSize;
}

+ (void)initialize;
- (void)textView:(id)arg1 prepareMenu:(id)arg2 forCharacterAtIndex:(unsigned long long)arg3 withEvent:(id)arg4;
- (id)accessibilityValue;
- (struct CGRect)accessibilityFrameForRange:(struct _NSRange)arg1;
- (struct _NSRange)accessibilityRangeForLine:(long long)arg1;
- (long long)accessibilityLineForIndex:(long long)arg1;
- (id)accessibilityStringForRange:(struct _NSRange)arg1;
- (BOOL)_shouldPrintByCallingDrawRect;
- (double)baselineOffsetFromBottom;
- (double)firstBaselineOffsetFromTop;
- (void)setAttributedStringValue:(id)arg1;
- (void)setFont:(id)arg1;
- (BOOL)_hasExtra10_11BordersInToolbars;
- (struct NSEdgeInsets)alignmentRectInsets;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
- (struct CGSize)intrinsicContentSize;
- (void)updateConstraints;
- (void)nsis_valueOfVariable:(id)arg1 didChangeInEngine:(id)arg2;
- (BOOL)_wantsMaxLayoutWidthFromEngine;
- (BOOL)_hasLayoutEngine;
- (struct CGSize)_intrinsicSizeWithinSize:(struct CGSize)arg1;
- (void)_updateLayoutDependentMetricsIfNeeded;
@property long long maximumNumberOfLines;
@property double preferredMaxLayoutWidth;
- (void)dealloc;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (BOOL)mouseDownCanMoveWindow;
- (BOOL)acceptsFirstMouse:(id)arg1;
- (BOOL)becomeFirstResponder;
@property(readonly) BOOL acceptsFirstResponder;
- (id)textView:(id)arg1 completions:(id)arg2 forPartialWordRange:(struct _NSRange)arg3 indexOfSelectedItem:(long long *)arg4;
- (BOOL)textView:(id)arg1 doCommandBySelector:(SEL)arg2;
- (void)textDidChange:(id)arg1;
- (void)textDidBeginEditing:(id)arg1;
- (BOOL)textShouldBeginEditing:(id)arg1;
- (void)textDidEndEditing:(id)arg1;
- (BOOL)textShouldEndEditing:(id)arg1;
- (BOOL)textView:(id)arg1 shouldChangeTextInRange:(struct _NSRange)arg2 replacementString:(id)arg3;
@property id <NSTextFieldDelegate> delegate;
- (BOOL)validateUserInterfaceItem:(id)arg1;
- (void)stopSpeaking:(id)arg1;
- (void)startSpeaking:(id)arg1;
- (void)viewDidEndLiveResize;
- (void)viewWillStartLiveResize;
- (void)selectText:(id)arg1;
- (BOOL)shouldBeTreatedAsInkEvent:(id)arg1;
- (void)mouseDown:(id)arg1;
- (void)setTitleWithMnemonic:(id)arg1;
- (id)previousText;
- (id)nextText;
- (void)setNextText:(id)arg1;
- (void)setPreviousText:(id)arg1;
@property BOOL allowsDefaultTighteningForTruncation;
@property unsigned long long bezelStyle;
- (void)setImportsGraphics:(BOOL)arg1;
- (BOOL)importsGraphics;
- (void)setAllowsEditingTextAttributes:(BOOL)arg1;
- (BOOL)allowsEditingTextAttributes;
@property(getter=isSelectable) BOOL selectable;
@property(getter=isEditable) BOOL editable;
@property(getter=isBezeled) BOOL bezeled;
@property(getter=isBordered) BOOL bordered;
- (void)setEnabled:(BOOL)arg1;
@property(copy) NSColor *textColor;
@property BOOL drawsBackground;
@property(copy) NSColor *backgroundColor;
@property(copy) NSAttributedString *placeholderAttributedString;
@property(copy) NSString *placeholderString;
- (BOOL)shouldSetFontSmoothingBackgroundColor;
- (void)setFrameSize:(struct CGSize)arg1;
- (BOOL)isFlipped;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)_commonTextFieldInit;
- (void)setErrorAction:(SEL)arg1;
- (SEL)errorAction;
- (id)ns_widgetType;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

