//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSTitlebarAccessoryViewController, NSTitlebarContainerView, NSTitlebarView, NSToolbar, NSToolbarFullScreenResetableAnimation, NSToolbarFullScreenWindow, NSWindow, _NSFullScreenTileDividerWindow;

__attribute__((visibility("hidden")))
@interface NSToolbarFullScreenWindowManager : NSObject
{
    BOOL _inLayout;
    NSWindow *_originalWindow;
    NSToolbarFullScreenWindow *window;
    NSToolbar *_toolbar;
    NSTitlebarAccessoryViewController *_auxiliaryViewController;
    NSToolbarFullScreenResetableAnimation *windowSlideOutAnimation;
    _NSFullScreenTileDividerWindow *_leftDividerWindow;
    _NSFullScreenTileDividerWindow *_rightDividerWindow;
    void *evtHandler;
    unsigned int autohideDisabledCounter;
    unsigned int forceWindowVisibleCounter;
    double _menuBarReveal;
    double _autohideHeight;
    double _lastSetAutohideHeight;
    BOOL hasAutoHideMask;
    BOOL menuBarIsShown;
    BOOL windowIsInFullScreen;
    BOOL settingAuxFrame;
    BOOL resizeContentWindowAfterToolbarAnimation;
    BOOL isForcingToolbarVisibleForSheet;
    BOOL isHandlingHotKeyEvent;
    BOOL forceAuxViewVisible;
    BOOL animatingToCorrectPosition;
    BOOL _toolbarWantsToAttachToMenubar;
    BOOL contentWindowInToolbarWindowMovementGroup;
    BOOL _performingLiveResize;
    BOOL setAsAttachedToMenuBar;
    BOOL setAsMergedWithMenuBar;
    BOOL _registeredForNotes;
    NSTitlebarContainerView *_titlebarContainerView;
    NSTitlebarView *_titlebarView;
    BOOL _toolbarWindowIsInheritingAppearanceFromParentWindow;
}

+ (id)fullScreenNotificationCenter;
+ (void)registerForTileNotifications;
@property NSTitlebarView *titlebarView; // @synthesize titlebarView=_titlebarView;
@property NSTitlebarContainerView *titlebarContainerView; // @synthesize titlebarContainerView=_titlebarContainerView;
@property BOOL toolbarWindowIsInheritingAppearanceFromParentWindow; // @synthesize toolbarWindowIsInheritingAppearanceFromParentWindow=_toolbarWindowIsInheritingAppearanceFromParentWindow;
@property(getter=isHandlingHotKeyEvent) BOOL handlingHotKeyEvent; // @synthesize handlingHotKeyEvent=isHandlingHotKeyEvent;
@property NSWindow *originalWindow; // @synthesize originalWindow=_originalWindow;
- (void)updateWindowVisibility;
- (void)forceUpdateMenuBarAttachmentTags:(BOOL)arg1;
- (void)updateMenuBarAttachmentTags;
- (void)_activeSpaceDidChangeNotification:(id)arg1;
- (void)_applicationDidResignActiveNotification:(id)arg1;
- (void)_applicationDidBecomeActiveNotification:(id)arg1;
- (void)_windowDidResignKeyNotification:(id)arg1;
- (void)_windowDidBecomeKeyNotification:(id)arg1;
- (id)description;
- (void)autohideHeightChanged;
- (void)_enableFullScreenForceVisibleForToolbar:(id)arg1;
- (void)_disableFullScreenForceVisibleForToolbar:(id)arg1;
- (void)_disableFullScreenAutohidingForToolbar:(id)arg1;
- (void)_enableFullScreenAutohidingForToolbar:(id)arg1;
- (void)updateTitlebarViewBlendingMode;
- (BOOL)autohideDisabled;
- (void)removeAsChildOfContentWindow;
- (void)addAsChildOfContentWindow;
- (id)window;
- (void)finalize;
- (void)dealloc;
- (void)dispose;
@property(retain, nonatomic) NSToolbar *toolbar;
- (void)updateWindowAndContentView;
- (void)setAuxiliaryViewController:(id)arg1;
- (id)auxiliaryViewController;
- (void)_addViewControllerToWindow;
- (struct CGPoint)_calcWindowTopLeft;
- (struct CGRect)_tileFrameForFullScreen;
- (void)_cacheTileRect:(struct CGRect)arg1;
- (void)_noteTileFrameChanged;
- (void)tile;
- (BOOL)_drivingLiveResize;
- (void)_removeRightTileDividerWindow;
- (void)_removeLeftTileDividerWindow;
- (void)_removeTileDividerWindows;
- (void)_updateTileDividerWindows;
- (void)_updateTileFrameUsingLiveResize:(struct CGRect)arg1;
- (id)currentDividerResizeDirections;
- (BOOL)performDividerDragWithEvent:(id)arg1 forResizeDirection:(long long)arg2;
- (void)_updateTileFrame;
- (void)_startLiveResize;
- (void)_endLiveResize;
- (void)retileForSpaceTileFrameChange;
- (BOOL)_calcAttachesToMenuBar;
- (id)mainLayoutView;
- (void)registerForWindowNotifications:(BOOL)arg1;
- (void)tileEndedLiveResizeNotification:(id)arg1;
- (void)tileStartedLiveResizeNotification:(id)arg1;
- (void)tileDidResizeNotification:(id)arg1;
- (void)windowDidChangeFullScreenStatus:(id)arg1;
- (void)_doDidEnterFullScreen;
- (void)windowDidChangeSheetNotification:(id)arg1;
- (void)updateWindowCorners;
- (void)finishAnimationIfSynchronous;
- (void)animateWindowToCorrectPositionIfNecessary;
- (void)updateWindowPositionAnimation:(double)arg1 startTop:(double)arg2;
- (double)correctWindowTopTarget;
- (BOOL)_isTiledUnderMenuBar;
- (void)toolbar:(id)arg1 didChangeFrameSizeFromOldSize:(struct CGSize)arg2;
- (void)layout;
- (void)toolbarDidChangeAttachesToMenuBar:(id)arg1;
- (void)updateMovementGroups;
- (unsigned long long)parentSpaceID;
- (unsigned long long)tileSpaceID;
- (void)resizeContentWindow;
- (double)_toolbarWindowContentScreenHeightForToolbar:(id)arg1;
- (BOOL)contentWindowShouldMakeRoomForToolbar;
- (void)updateWindowLayout;
- (void)updateWindowHeight;
- (void)updateContentViewRevealByMenuBar;
- (void)_updateContentViewWithEffectiveReveal:(double)arg1;
- (BOOL)_shouldDrawBaselineForEffectiveReveal:(double)arg1;
- (struct CGPoint)topCenterForSheet:(id)arg1;
- (void)updateWindowAlpha;
- (void)updateMenuBarScreenRevealHeight;
- (void)_makeWindowIfNecessary;
- (BOOL)_shouldRoundCorners;
- (struct CGSize)toolbarWindowSize;
- (double)visibleWindowHeight;
- (double)effectiveClampedAutohideHeight;
- (double)effectiveAutohideHeight;
- (double)desiredWindowHeight;
- (double)effectiveAuxiliaryViewMinHeight;
- (double)effectiveAuxiliaryViewMaxHeight;
- (unsigned long long)windowStyleMask;
- (id)screen;
- (struct NSToolbarFullScreenContentViewLayout_t)getToolbarLayout;
- (double)windowAnimationDuration;
- (id)init;

@end

