//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSTextAttachment.h"

@interface NSTokenAttachment : NSTextAttachment
{
    id _delegate;
    BOOL _needsSeparator;
}

- (id)_immediateActionAnimationControllerForRepresentedObject:(id)arg1 inTextView:(id)arg2;
- (id)_immediateActionAnimationControllerForCharacterAtIndex:(unsigned long long)arg1 inTextView:(id)arg2;
- (BOOL)prepareActionMenu:(id)arg1 forTextView:(id)arg2 atCharacterIndex:(unsigned long long)arg3 withEvent:(id)arg4;
- (id)_radialMenu;
- (void)sendPrepareMenu:(id)arg1 forTextView:(id)arg2 withEvent:(id)arg3;
- (void)setDelegate:(id)arg1;
- (id)delegate;
- (void)_setNeedsSeparator:(BOOL)arg1;
- (BOOL)_needsSeparator;
- (void)setAttachmentCell:(id)arg1;
- (id)attachmentCell;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithDelegate:(id)arg1;

@end

