//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSAutounbinder, NSDictionary, NSMapTable, NSStoryboard, NSViewController;

__attribute__((visibility("hidden")))
@interface NSWindowControllerMoreIVars : NSObject
{
    NSAutounbinder *autounbinder;
    long long cascadeNumber;
    struct CGPoint cascadePoint;
    NSMapTable *_externalObjectsTableForWindowLoading;
    NSArray *_topLevelObjectsToKeepAliveFromStoryboard;
    NSArray *_segueTemplates;
    NSStoryboard *_storyboard;
    NSDictionary *_segueDestinationOptions;
    BOOL _retainedSelf;
    NSViewController *_contentViewController;
}

@property(retain) NSViewController *contentViewController; // @synthesize contentViewController=_contentViewController;
@property BOOL retainedSelf; // @synthesize retainedSelf=_retainedSelf;
@property(retain) NSDictionary *segueDestinationOptions; // @synthesize segueDestinationOptions=_segueDestinationOptions;
@property(retain) NSStoryboard *storyboard; // @synthesize storyboard=_storyboard;
@property(retain) NSArray *segueTemplates; // @synthesize segueTemplates=_segueTemplates;
@property(retain) NSArray *topLevelObjectsToKeepAliveFromStoryboard; // @synthesize topLevelObjectsToKeepAliveFromStoryboard=_topLevelObjectsToKeepAliveFromStoryboard;
@property(retain) NSMapTable *externalObjectsTableForWindowLoading; // @synthesize externalObjectsTableForWindowLoading=_externalObjectsTableForWindowLoading;
- (void)dealloc;

@end

