//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString, _NSWindowFullScreenTransition;

@interface NSWindowFullScreenController : NSObject
{
    struct CGRect _savedFrame;
    _NSWindowFullScreenTransition *_fullScreenTransition;
    NSString *_stringWithSavedFrame;
    struct CGRect _savedScreenFrame;
    long long _savedScreenNumber;
    BOOL _toolbarWasHidden;
}

@property long long savedScreenNumber; // @synthesize savedScreenNumber=_savedScreenNumber;
@property struct CGRect savedScreenFrame; // @synthesize savedScreenFrame=_savedScreenFrame;
@property BOOL toolbarWasHidden; // @synthesize toolbarWasHidden=_toolbarWasHidden;
@property(copy) NSString *stringWithSavedFrame; // @synthesize stringWithSavedFrame=_stringWithSavedFrame;
@property struct CGRect savedFrame; // @synthesize savedFrame=_savedFrame;
- (void)dealloc;
@property(readonly) _NSWindowFullScreenTransition *fullScreenTransition; // @dynamic fullScreenTransition;

@end

