//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

__attribute__((visibility("hidden")))
@interface _NSXPCConnectionRequestedReplies : NSObject
{
    struct __CFDictionary *_replyTable;
    int _lock;
}

- (id)progressForSequence:(unsigned long long)arg1;
- (void)addSequence:(unsigned long long)arg1 withProgress:(id)arg2 cleanupBlock:(CDUnknownBlockType)arg3;
- (BOOL)removeSequence:(unsigned long long)arg1;
- (void)cleanup;
- (void)finalize;
- (void)dealloc;
- (id)init;

@end

