//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

__attribute__((visibility("hidden")))
@interface _NSXPCConnectionExpectedReplies : NSObject
{
    struct __CFDictionary *_replyTable;
    int _lock;
    unsigned long long _sequence;
    struct dispatch_group_s *_replyGroup;
}

- (void)addReplyCompletionBlockOnQueue:(struct dispatch_queue_s *)arg1 block:(CDUnknownBlockType)arg2;
- (void)decrementOutstandingReplyCount;
- (void)incrementOutstandingReplyCount;
- (id)progressForSequence:(unsigned long long)arg1;
- (void)removeSequence:(unsigned long long)arg1;
- (unsigned long long)sequenceWithProgress:(id)arg1;
- (void)finalize;
- (void)dealloc;
- (id)init;

@end

