//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Foundation/NSFormatter.h>

#import "NSCopying.h"
#import "NSObservable.h"
#import "NSObserver.h"
#import "NSSecureCoding.h"

@class NSLocale, NSString;

@interface NSPersonNameComponentsFormatter : NSFormatter <NSObservable, NSObserver, NSSecureCoding, NSCopying>
{
    id _private;
}

+ (BOOL)__abbreviationIsEnabledForLocale:(id)arg1;
+ (long long)__shortNameFormatForLocale:(id)arg1;
+ (long long)__nameOrderForLocale:(id)arg1;
+ (id)__supportedNameDefaultsFromLocale:(id)arg1;
+ (void)__registerDefaults;
+ (void)_setShortNameIsEnabled:(BOOL)arg1;
+ (BOOL)_shortNameIsEnabled;
+ (void)_setPreferNicknamesDefault:(BOOL)arg1;
+ (BOOL)_shouldPreferNicknames;
+ (void)_setShortNameFormat:(long long)arg1;
+ (long long)_defaultShortNameFormat;
+ (void)_setDefaultDisplayNameOrder:(long long)arg1;
+ (long long)_defaultDisplayNameOrder;
+ (id)_localizedShortNameForComponents:(id)arg1 withStyle:(long long)arg2 options:(unsigned long long)arg3;
+ (BOOL)supportsSecureCoding;
+ (id)_fallbackDescriptorForStyle:(long long)arg1 options:(unsigned long long)arg2;
+ (id)_relevantKeyPathsForStyle:(long long)arg1 options:(unsigned long long)arg2;
+ (id)_localizedDelimiterForComponents:(id)arg1 options:(unsigned long long)arg2;
+ (long long)_nameOrderWithOverridesForComponents:(id)arg1 options:(unsigned long long)arg2;
+ (id)_cjkLanguagesSet;
+ (BOOL)_isCJKScript:(id)arg1;
+ (id)__inferredDelimiterBetweenStringOne:(id)arg1 andStringTwo:(id)arg2 isPhonetic:(BOOL)arg3;
+ (id)__naiveDelimiterForCombinedNameString:(id)arg1;
+ (unsigned long long)__inferredScriptIndexForComponents:(id)arg1;
+ (unsigned long long)__inferredScriptIndexFromString:(id)arg1;
+ (id)__longestComponentFromComponents:(id)arg1;
+ (BOOL)__contents:(id)arg1 exclusivelyInCharacterSet:(struct USet *)arg2;
+ (struct USet *)__getCharacterSetWithPattern:(id)arg1;
+ (BOOL)isKatakana:(id)arg1;
+ (void)forEachExistingComponentWithComponents:(id)arg1 performBlock:(CDUnknownBlockType)arg2;
+ (id)_styleFormatterForStyle:(long long)arg1 masterFormatter:(id)arg2;
+ (id)__givenNameFirstOrdering;
+ (id)__familyNameFirstOrdering;
+ (id)localizedStringFromPersonNameComponents:(id)arg1 style:(long long)arg2 options:(unsigned long long)arg3;
+ (id)_formatterWithStyle:(long long)arg1 options:(unsigned long long)arg2;
+ (id)__localizedNameDefaults;
+ (id)__currentLocale;
- (BOOL)isEqualToFormatter:(id)arg1;
- (BOOL)isEqual:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (BOOL)getObjectValue:(out id *)arg1 forString:(id)arg2 errorDescription:(out id *)arg3;
- (long long)_nameOrderWithOverridesForComponents:(id)arg1;
- (long long)__localizedShortNameFormat;
- (long long)__localizedNameOrder;
- (BOOL)__localizedAbbreviationIsEnabled;
- (long long)__computedShortNameFormat;
- (long long)__computedNameOrderForComponents:(id)arg1;
- (id)annotatedStringFromPersonNameComponents:(id)arg1;
- (id)stringFromPersonNameComponents:(id)arg1;
@property long long style;
@property(getter=isPhonetic) BOOL phonetic;
@property NSLocale *_locale;
@property BOOL _ignoresFallbacks;
@property BOOL _forceGivenNameFirst;
@property BOOL _forceFamilyNameFirst;
- (void)dealloc;
- (id)init;
- (void)receiveObservedValue:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

