//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSView.h"

@class NSImageView, NSTextField;

@interface AppleAirplayMenuItemView : NSView
{
    NSTextField *_titleField;
    NSImageView *_iconImage;
    NSImageView *_checkImage;
}

@property(readonly) NSImageView *checkImage; // @synthesize checkImage=_checkImage;
@property(readonly) NSImageView *iconImage; // @synthesize iconImage=_iconImage;
@property(readonly) NSTextField *titleField; // @synthesize titleField=_titleField;
- (void)drawRect:(struct CGRect)arg1;

@end

