//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class AppleAirplayMenuItemView;

@interface AppleAirplayMenuItemViewLoader : NSObject
{
    AppleAirplayMenuItemView *_view;
}

@property(readonly) AppleAirplayMenuItemView *view; // @synthesize view=_view;

@end

