//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSMenuItem.h"

@class AppleAirplayMenuItemView;

@interface AppleAirplayMenuItem : NSMenuItem
{
    AppleAirplayMenuItemView *_itemView;
}

- (void)dealloc;
- (id)initWithTitle:(id)arg1 action:(SEL)arg2 keyEquivalent:(id)arg3;

@end

