//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface AppleIrisUnit : NSObject
{
    unsigned char _state;
    unsigned int _iris;
    unsigned int _notification;
}

- (unsigned char)resetState;
- (unsigned char)state;
- (void)dealloc;
- (id)initWithIris:(unsigned int)arg1 notificationCallback:(CDUnknownFunctionPointerType)arg2 port:(struct IONotificationPort *)arg3;

@end

