//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class SSAudioMonitor;

@interface AppleSoundSettings : NSObject
{
    BOOL _syncNeeded;
    BOOL _playVolumeKeyFeedback;
    SSAudioMonitor *_monitor;
}

+ (id)sharedSoundSettings;
- (void)setBeepVolume:(float)arg1;
- (float)beepVolume;
- (void)deviceChanged:(id)arg1;
- (BOOL)hasOutputDevice;
- (BOOL)canSetVolume;
- (BOOL)hasMute;
- (BOOL)hasBalance;
- (BOOL)hasVolume;
- (void)setBalance:(float)arg1;
- (float)balance;
- (void)setMainVolume:(float)arg1;
- (float)mainVolume;
- (void)setMute:(BOOL)arg1;
- (BOOL)isMuted;
- (void)setPlayUIEffects:(BOOL)arg1;
- (BOOL)playUIEffects;
- (void)beepFeedbackChanged:(id)arg1;
- (void)setPlayVolumeKeyFeedback:(BOOL)arg1;
- (void)postFeedbackChanged:(id)arg1;
- (BOOL)playVolumeKeyFeedback;
- (void)activateSettingsForCurrentUser;
- (void)setAlertSoundVolume:(float)arg1;
- (float)alertSoundVolume;
- (id)audioMonitor;
- (void)dealloc;
- (id)init;

@end

