//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface DiskInfo : NSObject
{
    BOOL _isDisc;
    int _blankDiskType;
    NSString *_finderName;
    NSString *_identifier;
    NSString *_mountpoint;
}

+ (id)diskInfoWithIdentifier:(id)arg1 blankDiskType:(int)arg2;
+ (id)diskInfoWithIdentifier:(id)arg1 mountpoint:(id)arg2 isDisc:(BOOL)arg3;
@property(readonly, nonatomic) BOOL isDisc; // @synthesize isDisc=_isDisc;
@property(readonly, nonatomic) int blankDiskType; // @synthesize blankDiskType=_blankDiskType;
@property(readonly, nonatomic) NSString *mountpoint; // @synthesize mountpoint=_mountpoint;
@property(readonly, nonatomic) NSString *identifier; // @synthesize identifier=_identifier;
@property(retain, nonatomic) NSString *finderName; // @synthesize finderName=_finderName;
- (void).cxx_destruct;
- (id)initWithIdentifier:(id)arg1 blankDiskType:(int)arg2;
- (id)initWithIdentifier:(id)arg1 mountpoint:(id)arg2 isDisc:(BOOL)arg3;

@end

