//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSMenuExtraController.h"

@class NSMenuExtra, NSMenuToolbar, NSView;

@interface NSMenuToolbarItem : NSObject <NSMenuExtraController>
{
    _Bool _inMotion;
    _Bool _menuVisible;
    NSMenuExtra *_menuExtra;
    NSMenuToolbar *_toolbar;
    NSView *_view;
    double _motionStartTime;
    double _motionDuration;
    struct CGPoint _motionStartLocation;
    struct CGPoint _motionDestLocation;
}

@property(nonatomic) struct CGPoint motionDestLocation; // @synthesize motionDestLocation=_motionDestLocation;
@property(nonatomic) struct CGPoint motionStartLocation; // @synthesize motionStartLocation=_motionStartLocation;
@property(nonatomic) double motionDuration; // @synthesize motionDuration=_motionDuration;
@property(nonatomic) double motionStartTime; // @synthesize motionStartTime=_motionStartTime;
@property(nonatomic) _Bool menuVisible; // @synthesize menuVisible=_menuVisible;
@property(readonly, nonatomic, getter=isInMotion) _Bool inMotion; // @synthesize inMotion=_inMotion;
@property(readonly, nonatomic) NSView *view; // @synthesize view=_view;
@property(nonatomic) __weak NSMenuToolbar *toolbar; // @synthesize toolbar=_toolbar;
@property(retain, nonatomic) NSMenuExtra *menuExtra; // @synthesize menuExtra=_menuExtra;
- (void).cxx_destruct;
- (BOOL)accessibilityPerformPress;
- (BOOL)accessibilityPerformCancel;
@property(getter=isAccessibilitySelected) BOOL accessibilitySelected;
@property(readonly) id accessibilityParent;
@property(readonly) struct CGRect accessibilityFrame;
- (id)axSize;
- (id)axPosition;
- (id)currentMenu;
- (id)axParent;
- (void)axPopUpMenu;
- (void)unload;
- (void)popUpMenu:(id)arg1;
- (void)cancelMenu;
- (void)drawMenuBackground:(BOOL)arg1;
- (void)setView:(id)arg1;
- (void)setLength:(double)arg1;
- (void)stepTowardsDestinationAtleastAsFarAs:(double)arg1 atTime:(double)arg2;
- (void)setDestinationOrigin:(struct CGPoint)arg1 travelTimeInSeconds:(double)arg2 startTime:(double)arg3;
- (void)setFrameOrigin:(struct CGPoint)arg1;
@property(readonly, nonatomic) struct CGPoint destination;
@property(readonly, nonatomic) struct CGRect frame;
- (void)dealloc;
- (id)initWithURL:(id)arg1;
- (id)initWithMenuExtra:(id)arg1;

@end

