//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@class NSBundle, NSData, NSMenuExtra;

@protocol NSMenuToolbarDelegate
- (void)removeMenuExtra:(NSMenuExtra *)arg1 afterDelay:(float)arg2;
- (void)removeMenuExtra:(NSMenuExtra *)arg1 fromExtra:(BOOL)arg2 fromUser:(BOOL)arg3;
- (void)moveMenuExtra:(NSMenuExtra *)arg1 toPosition:(unsigned long long)arg2;
- (NSMenuExtra *)createMenuExtra:(NSBundle *)arg1 atPosition:(unsigned long long)arg2 data:(NSData *)arg3;
@end

