//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSMenuToolbarItem.h"

@interface NSMenuToolbarGapItem : NSMenuToolbarItem
{
    struct CGRect _frame;
}

@property(readonly, nonatomic) struct CGRect frame; // @synthesize frame=_frame;
- (void)setFrameOrigin:(struct CGPoint)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

