//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSView.h"

#import "NSDraggingDestination.h"

@class NSMenuToolbar, NSString;

@interface NSMenuToolbarView : NSView <NSDraggingDestination>
{
    _Bool _inMouseDown;
    NSMenuToolbar *_toolbar;
    NSView *_lastLeftView;
    NSView *_lastRightView;
}

+ (id)dragIdentifier;
@property(nonatomic) _Bool inMouseDown; // @synthesize inMouseDown=_inMouseDown;
@property(retain, nonatomic) NSView *lastRightView; // @synthesize lastRightView=_lastRightView;
@property(retain, nonatomic) NSView *lastLeftView; // @synthesize lastLeftView=_lastLeftView;
@property(nonatomic) __weak NSMenuToolbar *toolbar; // @synthesize toolbar=_toolbar;
- (void).cxx_destruct;
- (id)fontSmoothingBackgroundColor;
- (BOOL)performDragOperation:(id)arg1;
- (void)draggingExited:(id)arg1;
- (unsigned long long)draggingUpdated:(id)arg1;
- (unsigned long long)draggingEntered:(id)arg1;
- (void)_beginViewDrag:(id)arg1 theEvent:(id)arg2 withImage:(id)arg3;
- (id)_createDragImage:(id)arg1;
- (void)rightMouseUp:(id)arg1;
- (void)mouseUp:(id)arg1;
- (void)mouseDown:(id)arg1;
- (void)rightMouseDown:(id)arg1;
- (id)handleMouseDown:(id)arg1 right:(_Bool)arg2;
- (id)_hitTest:(struct CGPoint *)arg1 dragTypes:(id)arg2;
- (id)hitTest:(struct CGPoint)arg1;
- (id)initWithToolbar:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

