//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSPoofView_CopiedFromKit, NSWindow;

@interface NSPoofAnimator : NSObject
{
    _Bool _releasesAfterPoofing;
    int _nextPoofFrame;
    NSWindow *_poofWindow;
    NSPoofView_CopiedFromKit *_poofWindowImageView;
}

+ (void)runPoofAtPoint:(struct CGPoint)arg1;
@property(nonatomic) _Bool releasesAfterPoofing; // @synthesize releasesAfterPoofing=_releasesAfterPoofing;
@property(nonatomic) int nextPoofFrame; // @synthesize nextPoofFrame=_nextPoofFrame;
@property(retain, nonatomic) NSPoofView_CopiedFromKit *poofWindowImageView; // @synthesize poofWindowImageView=_poofWindowImageView;
@property(retain, nonatomic) NSWindow *poofWindow; // @synthesize poofWindow=_poofWindow;
- (void).cxx_destruct;
- (void)updatePoofAnimation;
- (void)_donePoofing;
- (void)startPoofing:(struct CGSize)arg1;
- (void)setDragWindowOrigin:(struct CGPoint)arg1;
- (void)setDragWindowFrame:(struct CGRect)arg1;
- (void)dealloc;
- (id)init;

@end

