//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableArray, NSObject<OS_dispatch_source>;

@interface PeriodicMessageTrace : NSObject
{
    NSMutableArray *_blocks;
    NSObject<OS_dispatch_source> *_timer;
}

- (void).cxx_destruct;
- (void)addBlock:(CDUnknownBlockType)arg1;
- (id)initWithDomain:(id)arg1 preference:(id)arg2;

@end

