//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface SUISDocklingServer : NSObject
{
    id <SUISDocklingServerController> _controller;
}

@property(nonatomic) id <SUISDocklingServerController> controller; // @synthesize controller=_controller;
- (void)dealloc;
- (id)initWithController:(id)arg1;

@end

