//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#pragma mark Named Structures

struct LSItemInfoRecord {
    unsigned int _field1;
    unsigned int _field2;
    unsigned int _field3;
    struct __CFString *_field4;
};

struct _CSArchitecture {
    int cpu_type;
    int cpu_subtype;
};

struct _CSTypeRef {
    unsigned long long _field1;
    unsigned long long _field2;
};

struct _VMURange {
    unsigned long long _field1;
    unsigned long long _field2;
};

struct os_activity_entry_s {
    unsigned long long _field1;
    unsigned long long _field2;
    unsigned long long _field3;
    char *_field4;
    char *_field5;
    void *_field6;
    char *_field7;
    char *_field8;
    unsigned int _field9;
};

struct os_activity_process_s {
    void *_field1;
    void *_field2;
    void *_field3;
    void *_field4;
    unsigned long long _field5;
    char *_field6;
    char *_field7;
    int _field8;
};

struct proc_workqueueinfo {
    unsigned int _field1;
    unsigned int _field2;
    unsigned int _field3;
    unsigned int _field4;
};

