//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableSet, NSObject<OS_dispatch_queue>, NSObject<OS_xpc_object>;

@interface CSUIController : NSObject
{
    NSObject<OS_xpc_object> *_xpcConnection;
    NSObject<OS_dispatch_queue> *_activeHandlerQueue;
    NSMutableSet *_activeHandlers;
    BOOL _terminateWhenZeroActiveHandlers;
}

- (void).cxx_destruct;
- (void)applicationWillTerminate:(id)arg1;
- (unsigned long long)applicationShouldTerminate:(id)arg1;
- (void)applicationDidFinishLaunching:(id)arg1;
- (void)applicationWillFinishLaunching:(id)arg1;
- (void)dealloc;
- (id)init;
- (void)systemLocaleDidChange:(id)arg1;
- (void)logIncomingCommand:(long long)arg1 fromProcessIdentifier:(int)arg2 toBeHandledByClass:(Class)arg3;
- (BOOL)scheduleHandlerForMessageType:(int)arg1 connection:(id)arg2 object:(id)arg3;
- (int)messageTypeFromXPCObject:(id)arg1;
- (void)handleIncomingXPCMessage:(id)arg1 clientConnection:(id)arg2;
- (void)handleIncomingXPCConnection:(id)arg1;
- (void)invalidateXPC;
- (void)initializeXPC;

@end

