//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CSUIMessageHandler.h"

#import "NSAlertDelegate.h"

@class NSDictionary, NSString;

@interface LSLaunchErrorHandler : CSUIMessageHandler <NSAlertDelegate>
{
    NSDictionary *_errorDict;
    NSString *_helpAnchor;
}

+ (id)appStoreApplicationURL;
- (void).cxx_destruct;
- (BOOL)alertShowHelp:(id)arg1;
- (void)handleMessageWithCompletionHandler:(CDUnknownBlockType)arg1;
- (id)initWithMessageType:(int)arg1 connection:(id)arg2 object:(id)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

